# _config.yml

# Configuración de Jekyll
markdown: kramdown

# Configuración de GitHub Pages
repository: arandanos80/Tip_Of_The_Week/  # Cambia a tu nombre de usuario y nombre del repositorio
baseurl: ""  # Si tu repositorio no está en una subcarpeta, deja esto en blanco
url: "https://arandanos80.github.io"  # Cambia a tu nombre de usuario
source: docs  # Carpeta que contiene tu contenido
destination: ./docs/Tips  # Carpeta donde se generará el sitio

plugins:
  - jekyll-feed

# Configuración del Tema
theme:
  name: jekyll-theme-primer
  version: 0.6.0  # Reemplaza con la versión específica que desees utilizar

# Configuración de Sass
sass:
  sass_dir: _sass
  style: compressed

# Otras configuraciones según tus necesidades
